update slack notification

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -1,18 +1,12 @@
 name: Docker Image Build & Push for PR Updates
 
 on:
-  push:
-    branches-ignore:
-      - feature/test-automation
-    # paths:
-    #   - "docker-config-*.yaml"
-
-  # pull_request:
-  #   types: [opened, synchronize, reopened, edited]
-  #   branches:
-  #     - main
-  #   paths:
-  #     - "docker-config-*.yaml"
+  pull_request:
+    types: [opened, synchronize, reopened, edited]
+    branches:
+      - main
+    paths:
+      - "docker-config-*.yaml"
 
 jobs:
   detect-updates:
@@ -86,42 +80,42 @@ jobs:
         run: |
           docker build --no-cache . -f ${{ env.dockerfile_location }} -t ${{ env.account_number }}.dkr.ecr.${{ env.region }}.amazonaws.com/${{ env.ecr_repo_name }}:${{ env.release_tag }}
 
-  scan:
-    needs: [detect-updates, build]
-    runs-on: self-hosted
-    strategy:
-      matrix:
-        config_file: ${{ fromJson(needs.detect-updates.outputs.matrix || '[]') }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # scan:
+  #   needs: [detect-updates, build]
+  #   runs-on: self-hosted
+  #   strategy:
+  #     matrix:
+  #       config_file: ${{ fromJson(needs.detect-updates.outputs.matrix || '[]') }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Extract Variables from Config File
-        id: extract-vars
-        uses: ./.github/actions/extract-config-file
-        with:
-          config_file: ${{ matrix.config_file }}
+  #     - name: Extract Variables from Config File
+  #       id: extract-vars
+  #       uses: ./.github/actions/extract-config-file
+  #       with:
+  #         config_file: ${{ matrix.config_file }}
 
-      - name: Extract AWS Account Number
-        uses: ./.github/actions/extract-account-number
-        with:
-          acc_name: ${{ steps.extract-vars.outputs.acc_name }}
+  #     - name: Extract AWS Account Number
+  #       uses: ./.github/actions/extract-account-number
+  #       with:
+  #         acc_name: ${{ steps.extract-vars.outputs.acc_name }}
 
-      - name: Run Trivy Vulnerability Scan
-        run: |
-          IMAGE_TAG="$account_number.dkr.ecr.$region.amazonaws.com/$ecr_repo_name:$release_tag"
-          echo "🔍 Running Trivy scan on $IMAGE_TAG..."
-          trivy image --format table --ignore-unfixed --pkg-types os,library --severity HIGH,CRITICAL "$IMAGE_TAG" | tee trivy-results-${{ env.release_tag }}.txt
-          VULN_COUNT=$(trivy image --format json --ignore-unfixed --pkg-types os,library --severity HIGH,CRITICAL "$IMAGE_TAG" | jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH" or .Severity=="CRITICAL")] | length')
+  #     - name: Run Trivy Vulnerability Scan
+  #       run: |
+  #         IMAGE_TAG="$account_number.dkr.ecr.$region.amazonaws.com/$ecr_repo_name:$release_tag"
+  #         echo "🔍 Running Trivy scan on $IMAGE_TAG..."
+  #         trivy image --format table --ignore-unfixed --pkg-types os,library --severity HIGH,CRITICAL "$IMAGE_TAG" | tee trivy-results-${{ env.release_tag }}.txt
+  #         VULN_COUNT=$(trivy image --format json --ignore-unfixed --pkg-types os,library --severity HIGH,CRITICAL "$IMAGE_TAG" | jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH" or .Severity=="CRITICAL")] | length')
 
-          if [[ "${{ env.skip_vulnerability }}" == "true" ]]; then
-            echo "⚠️ Skipping vulnerability enforcement as per user input."
-          elif [[ "$VULN_COUNT" -gt 0 ]]; then
-            echo "❌ Vulnerabilities found. Failing the job."
-            exit 1
-          else
-            echo "✅ No HIGH/CRITICAL vulnerabilities found. Proceeding."
-          fi
+  #         if [[ "${{ env.skip_vulnerability }}" == "true" ]]; then
+  #           echo "⚠️ Skipping vulnerability enforcement as per user input."
+  #         elif [[ "$VULN_COUNT" -gt 0 ]]; then
+  #           echo "❌ Vulnerabilities found. Failing the job."
+  #           exit 1
+  #         else
+  #           echo "✅ No HIGH/CRITICAL vulnerabilities found. Proceeding."
+  #         fi
 
   # push:
   #   needs: [detect-updates, build, scan]
